version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=reservation
      - MYSQL_DATABASE=reservation
      - MYSQL_USER=reservation
      - MYSQL_PASSWORD=reservation

  reservation:
    image: reservation
    links:
      - mysql
    environment:
      - KEYCLOAK_CLIENT_SECRET=
    ports:
      - 8080:8080
